### ISSUE TITLE
ghost如果页面内容太宽显示不正常

### ISSUE THREAD

**Issue by y500** [bigfa/Puma#10]
如题，可以参考这个页面的展示 http://y500.me/blog/iosji-neng-shu/

**Comment by bigfa** [comment]
插入iframe的适合不是可以设置宽度么

**Comment by y500** [comment]
但是如果内容宽度超过页面的宽度，宽度设置页面的宽度的话，那就显示不全了

**Comment by bigfa** [comment]
设置成100%不就行了，实际上很少有人嵌入iframe的

2016年2月18日星期四，y500 notifications@github.com 写道：

**Comment by y500** [comment]
设置100%也会有显示不全的问题
不过确实很少有人用iframe的[尴尬]

**Comment by y500** [comment]
http://y500.me/blog/tag/life/ 你看这个页面，没用iframe也有这个问题

**Comment by bigfa** [comment]
截断问题很早就解决了，你升级下主题就好了。

**Comment by y500** [comment]
我好想昨天才clone下来的，我更新下试试

**Comment by y500** [comment]
commit ccd053190b501ee03ee3e135bac73c2fee145105
Author: bigfa jigoulee@gmail.com
Date:   Mon Dec 28 13:08:53 2015 +0800

确认是最新版本

**Comment by bigfa** [comment]
忘了你是ghost了，我更新下吧

**Comment by y500** [comment]
好的，thx！

**Comment by y500** [comment]
好了。
第一个问题我有嵌套了一层iframe解决了。
