### ISSUE TITLE
网站500，错误日志，求解

### ISSUE THREAD

**Issue by linarz** [bigfa/Puma#13]
FastCGI sent in stderr: "PHP message: P
HP Fatal error:  Cannot use object of type WP_Error as array in /var/www/zyl/htm
l/wp-content/themes/Puma/inc/update.php on line 9" while reading response header
 from upstream, client: 118.76.220.139, server: xxx.com .request: "GET / H
TTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xx.com"

**Comment by bigfa** [comment]
下载新的
