### ISSUE TITLE
提一个BUG，已受密码保护的文章，撤销密码保护后，输出摘要仍然是“这是一篇受保护的文章”

### ISSUE THREAD

**Issue by fourstring** [bigfa/Puma#14]
如题。可见我的站https://n4l.pw
首页有一篇“文学社字谜”文章，一开始加了密码，正常输出受保护摘要，现在撤销保护后仍然输出“这是一篇受保护的文章”的摘要。望尽快修复，感谢！

**Comment by bigfa** [comment]
这和主题没啥关系吧

2016年4月9日星期六，fourstring notifications@github.com 写道：

**Comment by fourstring** [comment]
和主题无关？WP的锅么

**Comment by bigfa** [comment]
wp super cache 的问题
