### ISSUE TITLE
希望您能回答我的问题

### ISSUE THREAD

**Issue by JamesDream** [bigfa/Puma#16]
主题非常不错，但是首页上的文章怎么让他不全部显示文章内容？
请求帮助
就是让首页展示的文章内容不全部展示出来，谢谢了

**Comment by haguo2008** [comment]
Post words break

set post thumbnail
use 
do something~~~
add

**Comment by Jigsawk** [comment]
有特色图的情况下自动缩略。
没有特色土的情况下手动在文章中添加more标签
