### ISSUE TITLE
post在使用feature图片时的一个问题

### ISSUE THREAD

**Issue by agui291** [bigfa/Puma#4]
bigfa，您好！非常喜欢你的puma主题，目前也在使用。

发现一个问题，当post设置了feature图片时，首页index的post列表无法使用代码（比如页面加密，删除线，护换行，内嵌视频代码等），但是post内页是无问题的。

请问这个问题能否修正，非常感谢！辛苦了！

**Comment by bigfa** [comment]
这个不是bug，如果设置了缩略图会自动截取摘要，你可以用其他方法添加超宽图片。

2015年11月16日星期一，agui291 notifications@github.com 写道：

**Comment by agui291** [comment]
谢谢，原来如此。

那我自己再研究下！
