### ISSUE TITLE
顶部社交网络显示问题

### ISSUE THREAD

**Issue by neveta** [bigfa/Puma#5]
您好bigfa，非常感谢您的免费theme，在使用过程中我有这么一个小问题一直挺困扰：
顶部社交网络的svg图标显示问题，在访问服务器本地svg图片时，浏览器可正常解析出所有图标，但将svg文件通过upyun的cdn服务调用访问，所有图标均不能解析出了，这是为何？已经正确同步svg文件到cdn服务器了，还望百忙中解惑，谢谢

出现这个问题的浏览器是pc端的chrome dev 48，手机端的safari，pc上的edge倒是没有这个问题

P.S win10的IE11无论那种svg访问方式均无法正常显示图标，可我看资料，9.0之后IE不是都能正常解析svg了么？

**Comment by neveta** [comment]
![chrome](https://cloud.githubusercontent.com/assets/11550551/11177434/8beed458-8c80-11e5-8e03-4e0a50ee3f58.png)

chrome dev 48.0.2560 显示不出

![edge](https://cloud.githubusercontent.com/assets/11550551/11177456/b638379a-8c80-11e5-95d2-af1e7af287fd.png)

edge正常

![code](https://cloud.githubusercontent.com/assets/11550551/11177492/e34a953e-8c80-11e5-8624-b85208f24b6a.png)

这是切换的cdn地址，已经再三确认svg同步到了cdn上，而且直接访问这个地址可以看到xml代码

**Comment by neveta** [comment]
是同源策略的问题？

**Comment by bigfa** [comment]
头部加上`<meta http-equiv="X-UA-Compatible" content="IE=edge">`应该可以解决IE的问题。
CDN那个可能是跨域问题，具体不是很清楚。

**Comment by bigfa** [comment]
IE不支持外链svg，就是个坑货……

2015年11月16日星期一，neveta notifications@github.com 写道：

**Comment by bigfa** [comment]
IE全家不支持外链SVG，不过我并不打算兼容这个东西，我会给出解决方案。
