### ISSUE TITLE
首先感谢你的主题，很稀饭；只不过使用过程中发现点击加载更多，之后的页面 WP-UTF8-Excerpt 失效

### ISSUE THREAD

**Issue by wekbs** [bigfa/Puma#6]
如题

**Comment by bigfa** [comment]
没用过那个插件，推测是插件启用了条件判断，只有在归档页和首页才生效。
所以才会在AJAX回调函数中没效果。

**Comment by CN-YuWei** [comment]
哦，这个插件很久没更新了，我再找找其他插件试试；之后会加上文章摘要功能咩？

**Comment by bigfa** [comment]
主题有摘要功能，文章里写的很清楚了。

2015年11月25日星期三，余炜 notifications@github.com 写道：

**Comment by CN-YuWei** [comment]
啊，抱歉没说仔细：一般很少会设置特色图像，也不会手动添加 more 标签。我先找找有插件可以用不，不行只能折腾代码，不是很在行，到时可能还得请教你！
多谢，打扰了！
