### ISSUE TITLE
本地测试时php报错

### ISSUE THREAD

**Issue by emuoiea** [bigfa/Puma#9]
完全不懂php，在下载了github上的最新puma主题在本地wamp上面测试时出错了。
提示：
 Warning: Illegal string offset 'domain' in C:\wamp\www\wordpress\wp-includes\l10n.php on line 418
....
....
本地wordpress版本4.3
望大师指点，很喜欢这个主题想自己mod一下~

**Comment by bigfa** [comment]
4.4+ 才能用
